all:
  children:
    orchestrator:
      hosts:
        trading-orchestrator:
          ansible_host: "{{ lookup('env', 'ORCHESTRATOR_IP') }}"
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    worker:
      hosts:
        trading-worker:
          ansible_host: "{{ lookup('env', 'WORKER_IP') }}"
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519