apiVersion: apps/v1
kind: Deployment
metadata:
  name: incredibleleverage-efficientfrontier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incredibleleverage
  template:
    metadata:
      labels:
        app: incredibleleverage
    spec:
      containers:
        - name: incredibleleverage-spxl
          image: incredibleleverage:spxl
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          env:
            - name: NODE_ENV
              value: "production"

        - name: incredibleleverage-ptir
          image: incredibleleverage:ptir
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          env:
            - name: NODE_ENV
              value: "production"

        - name: incredibleleverage-nvdl
          image: incredibleleverage:nvdl
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          env:
            - name: NODE_ENV
              value: "production"

        - name: incredibleleverage-hood
          image: incredibleleverage:hood
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          env:
            - name: NODE_ENV
              value: "production"

        - name: incredibleleverage-avl
          image: incredibleleverage:avl
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          env:
            - name: NODE_ENV
              value: "production"
      restartPolicy: Always
