apiVersion: apps/v1
kind: Deployment
metadata:
  name: incredibleleverage-efficientfrontier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incredibleleverage
  template:
    metadata:
      labels:
        app: incredibleleverage
    spec:
      containers:
        - name: incredibleleverage-spxl
          image: incredibleleverage:spxl
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          env:
            - name: NODE_ENV
              value: "production"

        - name: incredibleleverage-ptir
          image: incredibleleverage:ptir
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          env:
            - name: NODE_ENV
              value: "production"

        - name: incredibleleverage-nvdl
          image: incredibleleverage:nvdl
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          env:
            - name: NODE_ENV
              value: "production"

        - name: incredibleleverage-hood
          image: incredibleleverage:hood
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          env:
            - name: NODE_ENV
              value: "production"

        - name: incredibleleverage-avl
          image: incredibleleverage:avl
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          env:
            - name: NODE_ENV
              value: "production"

        - name: efficientfrontier-api
          image: efficientfrontier:api
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres:5432/efficientfrontier"

        - name: postgres
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "efficientfrontier"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: incredibleleverage
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: efficientfrontier-api
spec:
  selector:
    app: incredibleleverage
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
